"""Gate 4 — proof-of-concept execution (the only gate that can confirm).

Obtains a PoC (files + entrypoint), executes it in a sandbox, and interprets the
result via the exit-code contract (0 = demonstrated). A PoC that fires sets the
ladder status to ``confirmed``; one that runs but does not fire yields
``not_reproduced``; a timeout or executor error is fail-open (``inconclusive``).

The PoC comes from one of two places:
1. ``finding.evidence["poc"]`` — a dict ``{"files": {name: content}, "entrypoint": [...]}``.
   This lets a PoC be supplied deterministically (and lets this gate be tested
   with real execution).
2. Generated by an LLM ``backend`` when no PoC is attached. The generation prompt
   asks for the same JSON shape. If generation fails or is malformed, the gate is
   fail-open.

Verification: the execute-and-classify path is tested with the real local
executor and hand-written PoCs (confirmed / not-reproduced / timeout). The
LLM-generation path is tested with a scripted backend. Model PoC quality is not
measured.
"""

from __future__ import annotations

from crucible.backends.base import LLMBackend, LLMMessage
from crucible.sandbox.base import ExecutionStatus, SandboxExecutor
from crucible.schema.finding import Finding, ValidationGate, ValidationVerdict
from crucible.validators.ladder import Gate

_SYSTEM = (
    "You write minimal proof-of-concept scripts that demonstrate a specific "
    "vulnerability. The script must exit with status 0 if and only if it "
    "successfully demonstrates the issue, and non-zero otherwise. Keep it "
    "self-contained and dependency-free where possible."
)


class PoCGate(Gate):
    gate_id = ValidationGate.POC_SANDBOX

    def __init__(
        self,
        executor: SandboxExecutor,
        *,
        backend: LLMBackend | None = None,
        timeout_s: float = 30.0,
    ) -> None:
        self.executor = executor
        self.backend = backend
        self.timeout_s = timeout_s

    def _poc_from_backend(self, finding: Finding) -> dict | None:
        if self.backend is None:
            return None
        code = finding.evidence.get("code", "(source not provided)")
        prompt = (
            f"Vulnerability: {finding.rule_id} ({finding.cwe or 'no CWE'}) at "
            f"{finding.location.path}:{finding.location.start_line}\n"
            f"{finding.message}\n\nCode:\n{code}\n\n"
            'Respond as JSON: {"files": {"poc.py": "<script>"}, '
            '"entrypoint": ["python", "poc.py"]}'
        )
        try:
            resp = self.backend.complete(
                [LLMMessage("system", _SYSTEM), LLMMessage("user", prompt)],
                json_mode=True,
            )
        except Exception:
            return None
        if isinstance(resp.parsed, dict) and "files" in resp.parsed:
            return resp.parsed
        return None

    def evaluate(self, finding: Finding) -> ValidationVerdict:
        poc = finding.evidence.get("poc") or self._poc_from_backend(finding)
        if not isinstance(poc, dict) or not poc.get("files") or not poc.get("entrypoint"):
            return ValidationVerdict(
                gate=self.gate_id,
                passed=True,
                detail="no PoC available to execute; retained (fail-open)",
                failed_open=True,
            )

        result = self.executor.run(
            poc["files"], poc["entrypoint"], timeout_s=self.timeout_s
        )
        finding.evidence.setdefault("poc_run", {}).update(
            {
                "status": result.status.value,
                "exit_code": result.exit_code,
                "network_isolated": result.network_isolated,
                "duration_s": round(result.duration_s, 3),
            }
        )

        if result.status is ExecutionStatus.OK:
            return ValidationVerdict(
                gate=self.gate_id, passed=True, detail="PoC executed and demonstrated the issue"
            )
        if result.status is ExecutionStatus.FAILED:
            return ValidationVerdict(
                gate=self.gate_id,
                passed=False,
                detail=f"PoC ran (exit {result.exit_code}) but did not demonstrate the issue",
            )
        # TIMEOUT or ERROR -> cannot decide -> keep.
        return ValidationVerdict(
            gate=self.gate_id,
            passed=True,
            detail=f"PoC {result.status.value}; retained (fail-open)",
            failed_open=True,
        )
